export const ORGANS = [
  {
    id: "brain",
    name: "Brain",
    invention: "Environmental intelligence",
    ask: "What if a place could sense heat, water and energy together, and change its behaviour before the peak arrives?",
    gesture: ["Sense", "Process", "Decide", "Respond"],
    challenge: "Conditions that change together",
    accent: "intel",
    spot: { top: "1%", left: "38%", width: "24%", height: "12%" },
    focus: { origin: "50% 10%", transform: "scale(1.7)" },
    study: "The brain does not act on one signal. It senses many conditions at once, weighs them, and changes the response when the situation changes.",
    principle: "Sense, compare, decide, then respond. A useful decision is one that can be revised.",
    problem: "Heat, water demand, energy use and air quality in a city change together. Treating them as separate dashboards misses the moment they start to pull on each other.",
    translation: "Build a coordination layer that reads those conditions and retimes demand, instead of a system that always runs at full output.",
    concept: "A sensing-and-coordination concept for water, energy and heat. It is a design proposal for the exhibition, not a national control system.",
    impact: "In the model, anticipation lowers the peak. It does not create water or electricity. It changes when demand arrives.",
    research: "How such a layer would be governed, what it is allowed to switch, and what happens when its data is wrong.",
    controls: ["temperature", "waterDemand", "energyDemand", "airQuality"],
  },
  {
    id: "heart",
    name: "Heart",
    invention: "Energy circulation",
    ask: "What if energy moved toward the place that needs it, instead of staying where it was generated?",
    gesture: ["Generate", "Circulate", "Store", "Reallocate"],
    challenge: "Energy in the wrong place",
    accent: "circulation",
    spot: { top: "27%", left: "42%", width: "16%", height: "9%" },
    focus: { origin: "50% 31%", transform: "scale(1.7)" },
    study: "The heart does not store the body’s whole supply in one place. It keeps moving material towards the tissue that needs it now.",
    principle: "Circulation is a response to unequal need. Delivery matters as much as generation.",
    problem: "A hot, fast-growing city can have energy in one place and shortage in another at the same hour.",
    translation: "Treat generation, storage and demand as one loop: hold surplus, then release it where the load appears.",
    concept: "An adaptive circulation model. Solar supply in the model is only a scenario input, not a forecast of Oman’s grid.",
    impact: "When supply exceeds demand, the model stores the difference. When demand exceeds supply, it moves what it can and shows the gap that remains.",
    research: "Storage losses, land, cost, and which demands are allowed to be prioritised.",
    controls: ["sun", "energyDemand", "temperature"],
  },
  {
    id: "blood",
    name: "Blood",
    invention: "Resource circulation",
    ask: "What if water, energy, food and recoverable material moved as one circulation, instead of as separate sectors?",
    gesture: ["Carry", "Signal", "Deliver", "Return"],
    challenge: "Resources that never meet",
    accent: "circulation",
    spot: { top: "63%", left: "32%", width: "36%", height: "14%" },
    focus: { origin: "50% 68%", transform: "scale(1.4)" },
    study: "Blood carries oxygen, nutrients, signals and waste. One tissue can supply another because the stream connects them.",
    principle: "A living system circulates. Isolated supplies cannot answer a need somewhere else.",
    problem: "Water, energy, food, materials and recoverable waste are still easy to plan as if they never touched.",
    translation: "A circulation layer that moves an existing stream toward the demand under stress. It does not invent the resource.",
    concept: "Resource circulation for a connected Oman. The heart’s clean energy is what keeps the flow moving.",
    impact: "In the model, turning circulation on can shrink a shortage. The reading is a simulation assumption, not a measured national flow.",
    research: "Who is allowed to redirect a stream, what must never be interrupted, and the energy the circulation itself spends.",
    controls: ["energyDemand", "waterDemand"],
  },
  {
    id: "lungs",
    name: "Lungs",
    invention: "Environmental exchange",
    ask: "What if exchange happened across a large surface, and the surface answered when the air changed?",
    gesture: ["Surface", "Flow", "Exchange", "Adapt"],
    challenge: "Air that has to be exchanged",
    accent: "water",
    spot: { top: "21%", left: "28%", width: "44%", height: "14%" },
    focus: { origin: "50% 28%", transform: "scale(1.55)" },
    study: "Lungs exchange gases across an enormous folded surface while air keeps moving. The exchange is selective, and it changes with demand.",
    principle: "A large exchange surface plus controlled flow beats a single opening.",
    problem: "Dust, humidity and stale air are design conditions for coastal and desert cities, not side notes.",
    translation: "Use area and managed airflow for exchange, in landscape and in buildings, instead of assuming outdoor air is always clean enough.",
    concept: "A large-area exchange concept inspired by the lung’s surface, shown here as a design study.",
    impact: "Raising dust or lowering airflow in the model weakens exchange. The lung-inspired concept resists that, and it does not erase it.",
    research: "Maintenance in dust, water use of any planting, and whether the exchange is worth the energy that moves the air.",
    controls: ["dust", "humidity", "airQuality", "airflow"],
  },
  {
    id: "kidneys",
    name: "Kidneys",
    invention: "Selective water recovery",
    ask: "What if used water was separated, and only the fraction that cannot be recovered was left behind?",
    gesture: ["Select", "Recover", "Reuse", "Discard less"],
    challenge: "Water used once",
    accent: "water",
    spots: [
      { top: "40%", left: "34%", width: "8%", height: "6%" },
      { top: "41%", left: "57%", width: "8%", height: "6%" },
    ],
    focus: { origin: "50% 43%", transform: "scale(1.8)" },
    study: "A kidney does not throw the whole stream away. It separates, takes back what is still useful, and sends a smaller waste stream on.",
    principle: "Do not treat every part of a flow as equal. Recover first, then dispose of what remains.",
    problem: "Water that has been used once is often lost, while new water is expensive in energy and infrastructure.",
    translation: "Separate a used stream into recovered water, recoverable material and a concentrated remainder.",
    concept: "A selective recovery concept for the exhibition. Recovery in the model always has an energy cost.",
    impact: "Turn recovery up and the water gap narrows. The energy network feels the cost. That trade is the point.",
    research: "What quality of water the recovery is allowed to produce, and the brine or residue it still creates.",
    controls: ["contamination", "waterDemand", "energyDemand"],
  },
  {
    id: "liver",
    name: "Liver",
    invention: "Resource transformation",
    ask: "What if a mixed discard was told apart, and the useful part was changed instead of buried?",
    gesture: ["Separate", "Transform", "Recover", "Reuse"],
    challenge: "Waste treated as one pile",
    accent: "recover",
    spot: { top: "35%", left: "30%", width: "16%", height: "10%" },
    focus: { origin: "38% 40%", transform: "scale(1.7)" },
    study: "The liver changes substances. It does not only store them or pass them through. Some become useful. Some are made safer to remove.",
    principle: "Waste is a mixture. Transformation starts by telling the mixture apart.",
    problem: "A growing city that treats all discards as one pile pays for disposal and loses the fraction that could have been used.",
    translation: "Split a mixed stream into recoverable material, organic material, hazardous material and a true remainder.",
    concept: "A sorting-and-transformation concept. It does not claim a measured diversion rate for any Omani city.",
    impact: "In the model, more of the mix is routed to recovery and less is left as disposal. Hazardous material is not pretended away.",
    research: "Contamination between streams, markets for recovered material, and the energy the transformation itself requires.",
    controls: ["wasteMix"],
  },
  {
    id: "skin",
    name: "Skin",
    invention: "Adaptive building skin",
    ask: "What if a building’s outer layer changed with the sun, instead of enduring the same heat all day?",
    gesture: ["Sense the heat", "Change the skin", "Lower the load"],
    challenge: "Extreme heat on buildings",
    accent: "heat",
    spot: { top: "28%", left: "16%", width: "14%", height: "24%" },
    focus: { origin: "24% 42%", transform: "scale(1.45)" },
    study: "Skin is a living boundary. It protects, and it changes how much heat the body gains or loses as the surroundings change.",
    principle: "The outside layer should respond. A fixed shell is a guess about the weather.",
    problem: "Cooling is a large part of energy demand where heat and sun are extreme. A building that ignores the hour and the orientation stays expensive.",
    translation: "An external layer that changes shading and exposure as sun, hour and temperature change.",
    concept: "An adaptive second skin for buildings. No energy-saving percentage is claimed here.",
    impact: "In the model, the layer cuts heat load when the scenario is hot. Cooling demand follows. The energy system feels that change.",
    research: "Materials that survive dust and salt, glare, daylight, and whether occupants will accept a moving façade.",
    controls: ["temperature", "sun", "hour", "orientation"],
  },
  {
    id: "digestive",
    name: "Digestive system",
    invention: "Circular food resources",
    ask: "What if food and organic material were absorbed back into use, instead of leaving with everything else?",
    gesture: ["Input", "Process", "Absorb", "Return"],
    challenge: "Organic material leaving with the rest",
    accent: "recover",
    spot: { top: "46%", left: "36%", width: "28%", height: "14%" },
    focus: { origin: "50% 54%", transform: "scale(1.65)" },
    study: "Digestion takes an input apart, absorbs what can be used, and does not treat the whole meal as waste.",
    principle: "Useful material should be absorbed before the remainder is discarded.",
    problem: "Food and organic waste often leave the city in the same stream as everything else.",
    translation: "Give organic material its own path back to soil, energy or food production, after it has been separated.",
    concept: "A circular food-and-organic concept linked to the liver’s sorting. It is a study, not a farm design.",
    impact: "Turning it on in the model increases recovered material. It does not invent a yield.",
    research: "Safety of recovered nutrients, water and energy needed to run the loop, and who operates it.",
    controls: ["wasteMix", "waterDemand"],
  },
  {
    id: "skeleton",
    name: "Skeleton",
    invention: "Resilient structure",
    ask: "What if a structure shared its load, so one point was never asked to hold the whole stress?",
    gesture: ["Spread", "Support", "Yield locally", "Stay standing"],
    challenge: "Stress concentrating in one place",
    accent: "intel",
    spot: { top: "18%", left: "47%", width: "6%", height: "46%" },
    focus: { origin: "50% 40%", transform: "scale(1.35)" },
    study: "Bone carries load by distributing it through a structure. A single point is not asked to hold the whole body.",
    principle: "Resilience is shared load, not a thicker wall in one place.",
    problem: "Heat and structural demand arrive together on infrastructure. A design that concentrates stress fails at that point first.",
    translation: "Compare a concentrated structure with one that spreads load when stress rises.",
    concept: "A structural study for the exhibition model. It is not a structural engineering certificate.",
    impact: "The same load reads lower when the sharing strategy is on. Raise heat as well, and the stress climbs again.",
    research: "Real members, joints, codes, and cost. This screen only shows the logic of sharing load.",
    controls: ["structuralLoad", "temperature"],
  },
];

export const EXHIBITS = {
  brain: {
    crop: "50% 8%",
    zoom: 2.7,
    taken: "The brain keeps many signals in play at once: temperature, thirst, effort, air. It compares them, decides, and can change the decision. We take that sequence. Sense, process, decide, respond. We do not take the shape of the brain.",
    invention: "A thinking layer for Oman’s water, energy and heat. It reads them together and retimes what the other systems do before a peak arrives. It does not create water or electricity. It decides when they are asked for.",
  },
  heart: {
    crop: "52% 32%",
    zoom: 3.1,
    taken: "The heart does not make a supply and leave it in one chamber. It circulates. Blood carries what each tissue asks for, and the amount changes as the body changes. We take continuous circulation, storage in the flow, and delivery toward the place of need.",
    invention: "Energy that does not harm the place it comes from, then a circulation that keeps every other invention alive. Water recovery spends energy. The building skin lowers cooling demand. Exchange and waste transformation draw on the same flow. The heart generates, stores, and sends. If one region is short, the flow moves. If there is surplus, storage takes it.",
    beyond: "Being able to survive, and leaving enough for the next generation to survive, is the minimum. The aim is past that. People should be able to strive, enjoy, and develop quickly, while harm to any generation is not part of the plan. This heart is a design concept for energy that could support that pace. It is not a forecast of a national grid, and it claims no measured saving.",
  },
  blood: {
    crop: "50% 68%",
    zoom: 1.6,
    taken: "Blood is not the pump. It is the stream. It carries what each part needs, and it carries away what must leave. We take the idea that a healthy body is connected by flow, not by a pile of separate supplies.",
    invention: "A circulation for water, energy, food, materials and recoverable waste. When one place is short, the flow can move toward it. The stream does not create water or electricity. The heart’s clean energy is what keeps it moving. In the model, a shortage can ease when circulation is on. That easing is a simulation assumption, not a measured flow through a country.",
  },
  lungs: {
    crop: "50% 27%",
    zoom: 2.15,
    taken: "The lung is an exchange organ, not a waste organ. Its structure is an enormous folded surface. Air keeps moving across it, and the exchange changes when the body asks for more. We take the large surface, the flow, and the selective exchange.",
    invention: "An exchange idea for dust, humidity and air that has to be renewed. A large surface, with flow that can be managed, instead of one opening assumed to be enough. Raised dust or still air weakens the exchange in the model. The lung-inspired surface resists that. It does not erase it, and it does not claim to have cleaned a city.",
  },
  kidneys: {
    crop: "48% 41%",
    zoom: 2.45,
    taken: "A kidney does not throw the whole stream away. The structure filters, then takes back what is still useful, and sends on a smaller waste stream. We take selective filtration, reabsorption and recovery. We do not copy the organ. We copy the decision not to treat every drop as waste.",
    invention: "A water-recovery idea for a place where water used once is often lost. Used water enters. The stream is separated. Useful water is recovered. A concentrated remainder is what leaves. Recovery spends energy, so this invention is tied to the heart. In the model you can raise contamination or demand and watch the recovered stream and the energy draw change. Those readings are simulation assumptions, not a measured water saving.",
  },
  liver: {
    crop: "36% 39%",
    zoom: 2.7,
    taken: "The liver detoxifies by transforming. It does not call the whole mixture waste. It sorts, changes what it can, makes some of it useful, and prepares the rest to leave safely. We take separation, transformation and recovery.",
    invention: "A hope of zero waste. Mixed discards are told apart: material that can be recovered, organic material, hazardous material, and a true remainder. The path becomes use, separate, transform, recover, reuse. Hazardous material is not pretended away. Nothing here is a measured diversion rate for any city.",
  },
  skin: {
    crop: "20% 42%",
    zoom: 2.1,
    taken: "Skin is the body’s outer layer. It protects, and it changes how much heat is let in or let out as the surroundings change. A fixed shell would be a guess about the weather. We take the responding layer.",
    invention: "An outer layer for houses. In the extreme heat it closes against the sun, so less heat is driven indoors. When the day eases, the layer opens differently, so the building is not trapped in one setting. The aim is a house that depends less on air conditioning to fight the season, and therefore asks less of the energy system. No percentage of energy saved is claimed. In the model, heat load and cooling demand fall when the layer responds. That fall is a simulation assumption.",
  },
  digestive: {
    crop: "50% 54%",
    zoom: 2.3,
    taken: "Digestion takes an input apart and absorbs what can still be used. The whole meal is not treated as waste. We take input, process, absorb, recover.",
    invention: "A path for food and organic material, linked to the liver’s hope of zero waste. Organic matter is given its own return, toward soil, energy or food, after it has been separated. The model can increase recovered material. It does not invent a harvest.",
  },
  skeleton: {
    crop: "50% 38%",
    zoom: 1.7,
    taken: "Bone carries load by sharing it through a structure. One point is not asked to hold the body. We take distributed support, and the ability to keep standing as stress rises.",
    invention: "A structural idea for infrastructure that faces heat and load together. The same load can land on one member, or be shared across a frame. Sharing lowers the stress reading in the model. Raise the load or the heat and the stress climbs again. This is a study of the logic, not a structural certificate.",
  },
};

export const BEATS = [
  ["observe", "biology", "Observe", "study", "Biological observation"],
  ["ask", "biology", "Ask", "ask", "The engineering question"],
  ["principle", "principle", "Extract the principle", "principle", "Biological principle"],
  ["translate", "crossing", "Translate", "translation", "Engineering translation"],
  ["engineer", "innovation", "Engineer", "concept", "Design concept"],
  ["simulate", "innovation", "Simulate", "impact", "Simulation assumption"],
  ["apply", "innovation", "Apply to Oman", "problem", "The challenge"],
];

export const CHAPTERS = [
  ["question", "01", "The question"],
  ["teacher", "02", "The teacher"],
  ["investigation", "03", "The investigation"],
  ["system", "07", "The system"],
  ["prototype", "—", "The prototype"],
  ["future", "08", "The future"],
  ["close", "—", "Close"],
];

export const ORBIT = {
  brain: { top: "6%", left: "62%" },
  lungs: { top: "18%", left: "4%" },
  heart: { top: "28%", left: "68%" },
  liver: { top: "40%", left: "2%" },
  kidneys: { top: "46%", left: "66%" },
  skin: { top: "62%", left: "70%" },
  digestive: { top: "66%", left: "4%" },
  skeleton: { top: "80%", left: "38%" },
};

export const STEPS = [
  ["01", "Study nature", "study", "Biological observation"],
  ["02", "Extract the principle", "principle", "Biological principle"],
  ["03", "Oman problem", "problem", "Design question"],
  ["04", "Translate", "translation", "Engineering translation"],
  ["05", "Invent", "concept", "Design concept"],
  ["06", "Simulate", "controls", "Simulation assumption"],
  ["07", "2040 direction", "impact", "Conceptual direction"],
];

export const LAYERS = [
  "Skin",
  "Skeleton",
  "Organs",
  "Vessels",
  "Resource flows",
  "Environment",
  "Engineering",
  "Oman network",
];

export const FIELDS = {
  temperature: ["Outside temperature", "Cool", "Extreme heat"],
  sun: ["Sun intensity", "Low", "High"],
  waterDemand: ["Water demand", "Low", "High"],
  energyDemand: ["Energy demand", "Low", "High"],
  airQuality: ["Air quality", "Poor", "Clear"],
  dust: ["Dust", "Low", "High"],
  humidity: ["Humidity", "Dry", "Humid"],
  contamination: ["Contamination", "Light", "Heavy"],
  wasteMix: ["Mixed waste", "Light", "Heavy"],
  structuralLoad: ["Structural load", "Light", "Heavy"],
  airflow: ["Airflow", "Still", "Moving"],
  hour: ["Hour", "Night", "Evening"],
  orientation: ["Sun exposure", "Shaded", "Exposed"],
};

export const PROTOTYPES = ORGANS.map((organ) => ({
  id: organ.id,
  name: organ.name,
  invention: organ.invention,
  note: "Planned physical model for the exhibition.",
}));
