export const STATIONS = [
  {
    id: "brain",
    index: "01",
    name: "Brain",
    title: "Environmental intelligence",
    system: "The brain holds many signals at once. It compares them, decides, and can change the decision.",
    principleName: "Sense, then revise",
    principle: "A useful decision is one that can be revised when the situation changes.",
    challengeName: "Conditions that arrive together",
    question: "How could heat, water and energy be read as one situation, before the peak arrives?",
    steps: ["Sense", "Process", "Decide", "Respond"],
    path: [
      ["Biology", "Many signals, one revised decision"],
      ["Observation", "The brain does not act on a single reading"],
      ["Principle", "Sense, process, decide, respond"],
      ["Engineering", "A layer that retimes demand"],
      ["Oman", "Heat, water and energy move together"],
      ["Innovation", "Intelligence that does not create the resource"],
    ],
    observe: "Signals for heat, thirst and effort stay in play together. The response can change.",
    limit: "This is not a national control room. It does not create water or electricity.",
    controls: ["temperature", "waterDemand", "energyDemand", "airQuality"],
    readings: [["coolingDemand", "Cooling pull"], ["shortage", "Energy gap"], ["waterGap", "Water gap"]],
  },
  {
    id: "heart",
    index: "02",
    name: "Heart",
    title: "Energy circulation",
    system: "The heart does not keep the whole supply in one place. It keeps moving what each part is asking for.",
    principleName: "Circulate toward need",
    principle: "A living supply is judged by whether it can reach the place under load.",
    challengeName: "Energy in the wrong place",
    question: "How could clean energy be held, then sent where the load appears, without harming its source?",
    steps: ["Generate", "Circulate", "Store", "Send"],
    path: [
      ["Biology", "Continuous circulation"],
      ["Observation", "Delivery changes as the body changes"],
      ["Principle", "Move supply toward need"],
      ["Engineering", "Generate, store, release"],
      ["Oman", "Every other invention spends energy"],
      ["Innovation", "Energy that does not harm its source"],
    ],
    observe: "The stream changes amount and direction. Surplus can be held. Shortage is met by moving what exists.",
    limit: "A design concept for the exhibition. Not a forecast of a national grid, and not a measured saving.",
    beyond: "Survival is the minimum. The aim is a pace of life that can strive and develop, while harm to any generation is not part of the plan.",
    controls: ["sun", "energyDemand", "temperature"],
    readings: [["generation", "Generation"], ["storage", "Storage"], ["shortage", "Energy gap"]],
  },
  {
    id: "lungs",
    index: "03",
    name: "Lungs",
    title: "Environmental exchange",
    system: "The lung is an exchange organ, not a waste organ. A vast folded surface keeps air moving across it.",
    principleName: "Exchange across a surface",
    principle: "Balance depends on surface and flow. One opening is not an exchange.",
    challengeName: "Dust, humidity, fouled air",
    question: "How could a place renew air across a large surface when dust and stillness rise?",
    steps: ["Surface", "Flow", "Exchange", "Adapt"],
    path: [
      ["Biology", "A folded exchange surface"],
      ["Observation", "The exchange changes when the body asks for more"],
      ["Principle", "Large surface, managed flow"],
      ["Engineering", "Exchange that answers dust and humidity"],
      ["Oman", "Hot air, dust, and still corners"],
      ["Innovation", "A surface that resists fouled air"],
    ],
    observe: "Air keeps moving. The surface is the instrument. The lung does not store what it exchanges.",
    limit: "The model can raise the exchange. It does not claim to have cleaned a city.",
    controls: ["dust", "humidity", "airQuality", "airflow"],
    readings: [["exchange", "Exchange"], ["shortage", "Energy gap"]],
  },
  {
    id: "kidneys",
    index: "04",
    name: "Kidneys",
    title: "Water recovery",
    system: "The kidneys filter, take back what is still useful, and send on a smaller remainder.",
    principleName: "Selective recovery",
    principle: "Nature does not treat the whole stream as waste. It separates what can return.",
    challengeName: "Water scarcity",
    question: "How could used water be split, so more of what is useful comes back?",
    steps: ["Filter", "Reabsorb", "Recover", "Release"],
    path: [
      ["Biology", "Filtration, then reabsorption"],
      ["Observation", "The whole stream is not discarded"],
      ["Principle", "Selective recovery"],
      ["Engineering", "Separate, recover, release a remainder"],
      ["Oman", "Water used once is often lost"],
      ["Innovation", "Recovery that spends energy to return water"],
    ],
    observe: "A concentrate still leaves. Recovery is a decision, and it spends energy.",
    limit: "Recovered water in the model is a simulation assumption, not a measured saving.",
    controls: ["contamination", "waterDemand", "energyDemand"],
    readings: [["recoveredWater", "Recovered"], ["waterGap", "Still unmet"], ["shortage", "Energy draw"]],
  },
  {
    id: "liver",
    index: "05",
    name: "Liver",
    title: "Resource transformation",
    system: "The liver does not call the whole mixture waste. It sorts, changes what it can, and lets a remainder leave.",
    principleName: "Transform, then recover",
    principle: "A healthy system changes a mixture. It does not hide it.",
    challengeName: "Mixed waste",
    question: "How could a mixed stream be told apart, without pretending hazardous material vanished?",
    steps: ["Sort", "Transform", "Recover", "Release"],
    path: [
      ["Biology", "Detoxification by transformation"],
      ["Observation", "Some of the mixture can become useful"],
      ["Principle", "Separate, transform, recover"],
      ["Engineering", "Use, recover, name the remainder"],
      ["Oman", "Mixed discards and a hope of zero waste"],
      ["Innovation", "A stream split into recovery and remainder"],
    ],
    observe: "Hazardous material is still named. Nothing here is a measured diversion rate.",
    limit: "The model splits a mixture. It does not certify a city’s waste system.",
    controls: ["wasteMix"],
    readings: [["recoveredMaterial", "Recovered"], ["disposed", "Remainder"]],
  },
  {
    id: "skin",
    index: "06",
    name: "Skin",
    title: "Adaptive envelope",
    system: "Skin is a living boundary. It changes how much heat it lets through as the surroundings change.",
    principleName: "A responding outer layer",
    principle: "A fixed shell is a guess about the weather. A living layer answers the hour.",
    challengeName: "Extreme heat",
    question: "How could a house wear an outer layer that closes against the sun, and eases when the day does?",
    steps: ["Sense heat", "Close", "Open", "Ease the load"],
    path: [
      ["Biology", "An outer layer that regulates heat"],
      ["Observation", "The layer changes with the surroundings"],
      ["Principle", "Respond, do not endure one setting"],
      ["Engineering", "A second skin for buildings"],
      ["Oman", "Cooling is what makes extreme heat expensive"],
      ["Innovation", "Less heat treated as indoor load"],
    ],
    observe: "No share of energy saved is claimed. In the model, heat getting in falls when the layer responds.",
    limit: "That fall is a simulation assumption, not a measured bill.",
    controls: ["temperature", "sun", "hour", "orientation"],
    readings: [["heatLoad", "Heat getting in"], ["coolingDemand", "Cooling demand"]],
  },
  {
    id: "digestive",
    index: "07",
    name: "Digestive system",
    title: "Circular resources",
    system: "Digestion takes an input apart and absorbs what can still be used. The whole meal is not waste.",
    principleName: "Absorb before discarding",
    principle: "What can return is taken back before anything is called remainder.",
    challengeName: "Organic material lost in the mix",
    question: "How could food and organic material have their own path back to use?",
    steps: ["Input", "Process", "Absorb", "Return"],
    path: [
      ["Biology", "Break down, then absorb"],
      ["Observation", "Useful material is taken out of the mix"],
      ["Principle", "Recover before disposal"],
      ["Engineering", "A separate return for organic material"],
      ["Oman", "Food and organic matter leave with everything else"],
      ["Innovation", "A circular path linked to transformation"],
    ],
    observe: "The model can increase what is returned. It does not invent a harvest.",
    limit: "A study of the loop, not a farm design.",
    controls: ["wasteMix", "waterDemand"],
    readings: [["recoveredMaterial", "Returned"], ["disposed", "Remainder"]],
  },
  {
    id: "skeleton",
    index: "08",
    name: "Skeleton",
    title: "Resilient structure",
    system: "Bone carries a load by sharing it. One point is not asked to hold the body.",
    principleName: "Share the load",
    principle: "Resilience is a frame that spreads stress, not a thicker piece in one place.",
    challengeName: "Heat and load together",
    question: "How could infrastructure share stress when heat and demand arrive at once?",
    steps: ["Spread", "Support", "Yield locally", "Stay standing"],
    path: [
      ["Biology", "Load shared through a structure"],
      ["Observation", "Stress is not parked on one member"],
      ["Principle", "Distribute the load"],
      ["Engineering", "A frame instead of a single column"],
      ["Oman", "Heat and structural demand arrive together"],
      ["Innovation", "The same load reads lower when it is shared"],
    ],
    observe: "Raise the load or the heat and the stress climbs again.",
    limit: "A study of the logic, not a structural certificate.",
    controls: ["structuralLoad", "temperature"],
    readings: [["structuralStress", "Stress"]],
  },
];

export const SCENARIOS = [
  { id: "heat", name: "Extreme heat", patch: { temperature: 92, sun: 90, hour: 14, orientation: 84, energyDemand: 76, waterDemand: 72 } },
  { id: "water", name: "Water stress", patch: { waterDemand: 90, contamination: 78, energyDemand: 66, temperature: 80 } },
  { id: "energy", name: "High energy demand", patch: { energyDemand: 92, sun: 16, temperature: 74, hour: 20 } },
  { id: "air", name: "Air pollution", patch: { dust: 90, airQuality: 18, humidity: 68, airflow: 16 } },
  { id: "shortage", name: "Resource shortage", patch: { wasteMix: 88, structuralLoad: 82, waterDemand: 74, energyDemand: 80, temperature: 84 } },
];
